services:
  db:
    image: arm64v8/mysql
    ports:
      - 0.0.0.0:3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
